name: Glob Portal App Publisher
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: false
        default: develop
        description: Enter the tag to deploy
  push:
    branches:
      - 'develop'
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    name: 'Build Frontend'
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag }}
      - uses: actions/setup-node@v3
        with:
          node-version-file: ./ui/.nvmrc
      - working-directory: ./ui
        run: |
          npm ci
          npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: 'ui-dist'
          path: ui/dist
  glob:
    runs-on: ubuntu-latest
    name: 'Make a glob'
    needs: build-frontend
    steps:
      - name: Set up S3cmd cli tool
        uses: s3-actions/s3cmd@v1.5.0
        with:
          provider: digitalocean
          region: nyc3
          access_key: ${{ secrets.S3_ACCESS_KEY }}
          secret_key: ${{ secrets.S3_SECRET_KEY }}
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag }}
      - uses: actions/download-artifact@v3
        with:
          name: 'ui-dist'
          path: ui/dist
      - name: 'glob'
        uses: ./.github/actions/glob
        with:
          folder: 'ui/dist/*'
          docket: 'portal-app-publisher/desk.docket-0'
      - name: Commit and Push Glob
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add portal-app-publisher/desk.docket-0
          git commit -n -m "update glob: ${{ steps.glob.outputs.hash }} [skip actions]" || echo "No changes to commit"
          INPUT=${{ github.event.inputs.tag }}
          BRANCH=${INPUT:-"develop"}
          git pull origin $BRANCH --rebase --autostash
          git push
